package hackathon.luxoft.eveterandemo.Bot;

public enum BotState {
    NONE,
    GREETING,
    VETERAN,
    VETERAN_HELPER,
    VETERAN_FAMILY_MEMBER,
    VETERAN_INPUT_IPN,
    VETERAN_INPUT_BIRTHDAY,
    VETERAN_INPUT_SEX,
    VETERAN_INPUT_PASSPORT_TYPE,
    VETERAN_PASSPORT,
    VETERAN_IDPASSPORT,
    VETERAN_INPUT_ISSUED_DATE,
    VETERAN_INPUT_ISSUED_BY,
    VETERAN_INPUT_INPUT_REGISTRATION_PLACE,
    VETERAN_INPUT_RESIDENCE_PLACE_MATCH,
    VETERAN_INPUT_RESIDENCE_PLACE,
    VETERAN_INPUT_EDUCATIONAL_LEVEL,
    VETERAN_INPUT_SPECIALITY,
    VETERAN_INPUT_PHONE,
    VETERAN_INPUT_EMAIL,
    VETERAN_SUBMIT,
    VETERAN_CONGRATS
}
